% Launch the main VAC plotting scripts.
%
% This script is a simple entry point for generating the main VAC figures.
% Keep detailed plot logic inside focused plot scripts.
%
% Inputs:
%   Uses the input CSV files configured inside each plotting script.
%
% Outputs:
%   Figures generated by each plotting script.
%
% Note: Add the plotting files to this launcher plot only if needed,
% otherwise the plotting files should be executable by itself alone.
%


clc;
clear;
close all;

% -------------------- Main Plot Scripts --------------------
run("plot_metrics.m");
run("plot_windowed_DSJ_trajectory_heatmap.m");